### ISSUE TITLE
Criar documentação sobre gitpages

### ISSUE THREAD

**Issue by giovanniacg** [giovanniacg/tutorial-git#28]
# GitPages

Deve-se criar um arquivo .md para falar um pouco sobre como funciona a git page e dar exemplos de ferramentas que podem ser utilizadas para seu gerenciamento.

## Tasks

- [x] Explicar como a gitpage funciona
- [x] Criar passo a passo do que deve ser feito
- [x] Dar exemplos de ferramentas que auxiliem na criação da page
